from typing import Protocol

from community.domain.community import Community
from community.domain.community_status import CommunityStatus
from community.domain.feature_request import FeatureRequest
from community.domain.feature_status import FeatureStatus
from community.domain.fund import CommunityFund, FundDistribution, FundTransaction
from community.domain.invite_code import CommunityInviteCode


class CommunityRepository(Protocol):
    def find_by_id(self, community_id: str) -> Community | None: ...
    def save(self, community: Community) -> None: ...
    def search(
        self,
        owner_id: str | None = None,
        member_user_id: str | None = None,
        status: CommunityStatus | None = None,
        keyword: str | None = None,
    ) -> list[Community]: ...


class FeatureRequestRepository(Protocol):
    def find_by_id(self, request_id: str) -> FeatureRequest | None: ...
    def save(self, feature_request: FeatureRequest) -> None: ...
    def find_by_community(self, community_id: str) -> list[FeatureRequest]: ...
    def find_all(
        self,
        community_id: str | None = None,
        status: FeatureStatus | None = None,
        author_id: str | None = None,
    ) -> list[FeatureRequest]: ...


class FundRepository(Protocol):
    def find_by_community(self, community_id: str) -> CommunityFund | None: ...
    def save(self, fund: CommunityFund) -> None: ...
    def save_transaction(self, tx: FundTransaction) -> None: ...
    def save_distribution(self, dist: FundDistribution) -> None: ...
    def list_transactions(self, fund_id: str) -> list[FundTransaction]: ...
    def list_distributions(self, fund_id: str) -> list[FundDistribution]: ...


class CommunityInviteCodeRepository(Protocol):
    def find_by_code(self, code: str) -> CommunityInviteCode | None: ...
    def find_by_id(self, code_id: str) -> CommunityInviteCode | None: ...
    def find_by_community(self, community_id: str) -> list[CommunityInviteCode]: ...
    def save(self, invite_code: CommunityInviteCode) -> None: ...
    def delete(self, code_id: str) -> None: ...


class CommunityUnitOfWork(Protocol):
    communities: CommunityRepository
    feature_requests: FeatureRequestRepository
    fund: FundRepository
    invite_codes: CommunityInviteCodeRepository

    def __enter__(self) -> "CommunityUnitOfWork": ...
    def __exit__(self, *args: object) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
