"""Add cohort learning tables

Revision ID: 06b9d2e9cc51
Revises: 2f8a61f098ef
Create Date: 2026-04-15 17:28:01.202834

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "06b9d2e9cc51"
down_revision: Union[str, Sequence[str], None] = "2f8a61f098ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "learning_cohorts",
        sa.Column("cohort_id", sa.String(length=255), nullable=False),
        sa.Column("master_id", sa.String(length=255), nullable=False),
        sa.Column("module_id", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "forming",
                "active",
                "completing",
                "graduated",
                "cancelled",
                name="cohortstatus",
            ),
            nullable=False,
        ),
        sa.Column("formed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("cohort_id"),
    )
    op.create_table(
        "module_progressions",
        sa.Column("module_id", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("master_id", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("module_id"),
    )
    op.create_table(
        "topic_competencies",
        sa.Column("competency_id", sa.String(length=255), nullable=False),
        sa.Column("learner_id", sa.String(length=255), nullable=False),
        sa.Column("topic_id", sa.String(length=255), nullable=False),
        sa.Column("cohort_id", sa.String(length=255), nullable=False),
        sa.Column("achieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("competency_id"),
    )
    op.create_table(
        "cohort_memberships",
        sa.Column("membership_id", sa.String(length=255), nullable=False),
        sa.Column("learner_id", sa.String(length=255), nullable=False),
        sa.Column("cohort_id", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "learner", "topic_expert", "module_curator", "master", name="cohortrole"
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["cohort_id"], ["learning_cohorts.cohort_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("membership_id"),
    )
    op.create_table(
        "topics",
        sa.Column("topic_id", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("module_id", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["module_id"], ["module_progressions.module_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("topic_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("topics")
    op.drop_table("cohort_memberships")
    op.drop_table("topic_competencies")
    op.drop_table("module_progressions")
    op.drop_table("learning_cohorts")
    # Drop PostgreSQL enum types created by this migration
    op.execute("DROP TYPE IF EXISTS cohortstatus")
    op.execute("DROP TYPE IF EXISTS cohortrole")
    # ### end Alembic commands ###
