"""Initial schema: auth and project collaboration tables

Revision ID: 2f8a61f098ef
Revises:
Create Date: 2026-04-08 22:37:30.983654

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2f8a61f098ef"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_users",
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "feature_requests",
        sa.Column("request_id", sa.String(length=255), nullable=False),
        sa.Column("author_id", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "submitted",
                "planned",
                "in_progress",
                "done",
                "rejected",
                name="featurestatus",
            ),
            nullable=False,
        ),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("priority", sa.String(length=50), nullable=True),
        sa.Column("admin_notes", sa.Text(), nullable=True),
        sa.Column("metadata", postgresql.JSON(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("request_id"),
    )
    op.create_table(
        "projects",
        sa.Column("project_id", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("owner_id", sa.String(length=255), nullable=False),
        sa.Column("max_members", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "recruiting",
                "active",
                "completed",
                "suspended",
                "cancelled",
                name="projectstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "previous_status",
            sa.Enum(
                "draft",
                "recruiting",
                "active",
                "completed",
                "suspended",
                "cancelled",
                name="projectstatus",
            ),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("project_id"),
    )
    op.create_table(
        "applications",
        sa.Column("application_id", sa.String(length=255), nullable=False),
        sa.Column("applicant_id", sa.String(length=255), nullable=False),
        sa.Column("project_id", sa.String(length=255), nullable=False),
        sa.Column(
            "desired_role",
            sa.Enum(
                "owner", "admin", "mentor", "member", "observer", name="projectrole"
            ),
            nullable=False,
        ),
        sa.Column("motivation", sa.Text(), nullable=False),
        sa.Column(
            "applicant_skills", postgresql.JSON(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("pending", "accepted", "rejected", name="applicationstatus"),
            nullable=False,
        ),
        sa.Column("reviewed_by", sa.String(length=255), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.project_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("application_id"),
    )
    op.create_table(
        "auth_credentials",
        sa.Column("credential_id", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("provider_user_id", sa.String(length=320), nullable=False),
        sa.Column("hashed_secret", sa.String(length=512), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["auth_users.user_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("credential_id"),
        sa.UniqueConstraint("user_id", "provider", name="uq_user_provider"),
    )
    op.create_table(
        "memberships",
        sa.Column("membership_id", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("project_id", sa.String(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "owner", "admin", "mentor", "member", "observer", name="projectrole"
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("joined_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.project_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("membership_id"),
    )
    op.create_table(
        "project_skill_tags",
        sa.Column("project_id", sa.String(length=255), nullable=False),
        sa.Column("skill_value", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.project_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("project_id", "skill_value"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_skill_tags")
    op.drop_table("memberships")
    op.drop_table("auth_credentials")
    op.drop_table("applications")
    op.drop_table("projects")
    op.drop_table("feature_requests")
    op.drop_table("auth_users")
    # Drop enum types created by upgrade
    sa.Enum(name="featurestatus").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="projectstatus").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="projectrole").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="applicationstatus").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
