"""Domain ports (driven interfaces) for the Guarantorship bounded context."""

from __future__ import annotations

from typing import Protocol

from guarantorship.domain.complaint import Complaint
from guarantorship.domain.deal import Deal
from guarantorship.domain.guarantee_request import GuaranteeRequest
from guarantorship.domain.guarantorship import Guarantorship
from guarantorship.domain.platform_settings import PlatformSettings
from guarantorship.domain.user_deposit import UserDeposit
from guarantorship.domain.zero_circle import ZeroCircle


class GuaranteeRequestRepository(Protocol):
    def save(self, request: GuaranteeRequest) -> None: ...
    def find_by_id(self, request_id: str) -> GuaranteeRequest | None: ...
    def find_incoming(self, guarantor_id: str) -> list[GuaranteeRequest]: ...
    def find_outgoing(self, ward_id: str) -> list[GuaranteeRequest]: ...
    def find_active_guarantors_for(self, ward_id: str) -> list[str]: ...


class GuarantorshipRepository(Protocol):
    def save(self, guarantorship: Guarantorship) -> None: ...
    def find_by_id(self, guarantorship_id: str) -> Guarantorship | None: ...
    def find_by_ward(self, ward_id: str) -> list[Guarantorship]: ...
    def find_by_guarantor(self, guarantor_id: str) -> list[Guarantorship]: ...
    def count_wards_for_guarantor(self, guarantor_id: str) -> int: ...


class UserDepositRepository(Protocol):
    def save(self, deposit: UserDeposit) -> None: ...
    def find_by_id(self, deposit_id: str) -> UserDeposit | None: ...
    def find_by_ward(self, ward_id: str) -> list[UserDeposit]: ...
    def find_by_guarantor(self, guarantor_id: str) -> list[UserDeposit]: ...
    def find_by_ward_and_guarantor(
        self, ward_id: str, guarantor_id: str
    ) -> UserDeposit | None: ...


class DealRepository(Protocol):
    def save(self, deal: Deal) -> None: ...
    def find_by_id(self, deal_id: str) -> Deal | None: ...
    def find_by_participant(self, user_id: str) -> list[Deal]: ...


class ComplaintRepository(Protocol):
    def save(self, complaint: Complaint) -> None: ...
    def find_by_id(self, complaint_id: str) -> Complaint | None: ...
    def find_by_deal(self, deal_id: str) -> list[Complaint]: ...
    def find_open_for_voter(self, voter_id: str) -> list[Complaint]: ...


class PlatformSettingsRepository(Protocol):
    def get(self) -> PlatformSettings: ...
    def save(self, settings: PlatformSettings) -> None: ...


class ZeroCircleRepository(Protocol):
    def save(self, circle: ZeroCircle) -> None: ...
    def find_by_id(self, circle_id: str) -> ZeroCircle | None: ...
    def find_open(self) -> list[ZeroCircle]: ...
    def find_active_circle_for_user(self, user_id: str) -> ZeroCircle | None: ...


class GuarantorshipUnitOfWork(Protocol):
    """Unit of Work for the Guarantorship context."""

    requests: GuaranteeRequestRepository
    guarantorships: GuarantorshipRepository
    deposits: UserDepositRepository
    deals: DealRepository
    complaints: ComplaintRepository
    settings: PlatformSettingsRepository
    circles: ZeroCircleRepository

    def __enter__(self) -> "GuarantorshipUnitOfWork": ...
    def __exit__(self, *args: object) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
